### ISSUE TITLE
Where is 64 bits?

### ISSUE THREAD

**Issue by kisssko** [airabinovich/finalArquitectura#1]
MIPS R4000 is the CPU with 64 bits architecture (ISA-3). I see, there is something like MIPS ISA-1, whitch is the 32 bits architecture. It is not MIPS R4000. It looks like MIPS R2000.

**Comment by airabinovich** [comment]
Hello @kisssko and thanks for the comment, I didn't know that. But this repository is a university project I made a few years ago, it'll never be expanded to new ISAs
